server:
    port: 8081

eureka:
    instance:
        hostname: todo-service-registry
        prefer-ip-address: true
    client:
        service-url:
        default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}